app.config(["$routeProvider",function($routeProvider){
    $routeProvider.when("/zhuce",{
        templateUrl:"pages/denglu/zhuce.html",
        controller:"zhuceCtrl"
    }).when("/zhuce1",{
        templateUrl:"pages/denglu/zhuce1.html",
        controller:"zhuce1Ctrl"
    }).when("/zhuce2",{
        templateUrl:"pages/denglu/zhuce2.html",
        controller:"zhuce2Ctrl"
    }).when("/zhuce3",{
        templateUrl:"pages/denglu/zhuce3.html",
        controller:"zhuce3Ctrl"
    }).when("/tuijian",{
        templateUrl:"pages/My/tuijian/tuijian.html",
        controller:"tuijianCtrl"
    }).when("/gerenxinxi",{
        templateUrl:"pages/My/gerenxinxi/gerenxinxi.html",
        controller:"gerenxinxiCtrl"
    }).when("/banben",{
        templateUrl:"pages/My/banben/banben.html",
        controller:"banbenCtrl"
    }).when("/yijian",{
        templateUrl:"pages/My/yijian/yijian.html",
        controller:"yijianCtrl"
    }).when("/shezhi",{
        templateUrl:"pages/My/shezhi/shezhi.html",
        controller:"shezhiCtrl"
    }).when("/wodexiaoxi",{
        templateUrl:"pages/wode/wodexinxi/wodexiaoxi.html",
        controller:"wodexiaoxiCtrl"
    }).when("/wodeziliao",{
        templateUrl:"pages/wode/wodeziliao/wodeziliao.html",
        controller:"wodeziliaoCtrl"
    }).when("/wenzhang",{
        templateUrl:"pages/zhangjie/wenzhang/zhangjie.html",
        controller:"wenzhangCtrl"
    }).when("/wodibiji",{
        templateUrl:"pages/zhangjie/wodibiji/biji.html",
        controller:"bijiCtrl"
    }).when("/mulu",{
        templateUrl:"pages/zhangjie/mulu/mulu.html",
        controller:"muluCtrl"
    }).when("/shuye1",{
        templateUrl:"pages/book-page/shuye1/shuye.html",
        controller:"shuye1Ctrl"
    }).when('/shuye1/shuye3',{
        templateUrl:"pages/book-page/shuye3/shuye.html",
        controller:"shuye3Ctrl"
    }).when('/shuye6',{
        templateUrl:"pages/book-page/shuye6/shuye.html",
        controller:"shuye6Ctrl"
    }).when('/shuye4',{
        templateUrl:"pages/book-page/shuye4/shuye.html",
        controller:"shuye4Ctrl"
    }).when('/shuye5',{
        templateUrl:"pages/book-page/shuye5/shuye.html",
        controller:"shuye5Ctrl"
    }).when("/shucheng",{
		templateUrl:"pages/shucheng/jingxuan/jingxuan.html",
		controller:"jingxuanCtrl"
	}).when("/bangdan",{
		templateUrl:"pages/shucheng/bangdan/bangdan.html",
		controller:"bangdanCtrl"
	}).when("/fenlei",{
		templateUrl:"pages/shucheng/fenlei/fenlei.html",
		controller:"fenleiCtrl"
	})
}])

